# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none
pr: none
# can replace the git hub action build and push trigger
# tags:
#   include:
#   - v2.*
resources:
  repositories:
    - repository: devops
      type: github
      endpoint: MapColonies
      name: MapColonies/Devops
      ref: refs/heads/master

variables:
  HELM_EXPERIMENTAL_OCI: 1

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          name: aro-nonprod-pool
        steps:
          - checkout: self
          - template: azure-pipelines/buildAndPush.yaml@devops
            parameters:
              # the service connection name for the docker registry Default is ACR
              # dockerRegistryServiceConnection:
              # the path to the docker file Default is [root Folder]/DockerFile
              dockerfilePaths:
                - name: 3d-model-ingestion-service
                  path: '$(Build.SourcesDirectory)/Dockerfile'
              # the url of the helm registry Default [ACR non prod registry url]
              # helmrRegistryUrl:
              # the path to the helm folder. Default is [root Folder]/helm
              # helmFolderPath:
              # the name of the app. the name of the image and the name of the chart will be the same.
              #appName: mapproxinator
              appName: '3d-model-ingestion-service'
              teamName: '3D'
              bumpPipeline: '95'
